// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: accounts.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :exec
INSERT INTO accounts (id, name, kind, balance, updated_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateAccountParams struct {
	ID        uuid.UUID
	Name      string
	Kind      string
	Balance   int64
	UpdatedAt time.Time
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.ExecContext(ctx, createAccount,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.Balance,
		arg.UpdatedAt,
	)
	return err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, id)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, name, kind, balance, updated_at, created_at FROM accounts WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Balance,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, name, kind, balance, updated_at, created_at FROM accounts ORDER BY kind, name
`

func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Balance,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :exec
UPDATE accounts SET name = $2, balance = $3, updated_at = $4
WHERE id = $1
`

type UpdateAccountParams struct {
	ID        uuid.UUID
	Name      string
	Balance   int64
	UpdatedAt time.Time
}

// 更新は名称と残高だけ。kind をここに含めない。
//
// PATCH /api/accounts/{id} が更新するのは名称・残高のみ（design.md 5.1）。
// kind を cash から investment に変えられると、その口座が実質資産の計算から
// 丸ごと消える（CLAUDE.md 不変条件1）。API に無い操作を SQL 側にも残さない。
// 種別を変えたくなったら、作り直すか専用のクエリを足す。
func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) error {
	_, err := q.db.ExecContext(ctx, updateAccount,
		arg.ID,
		arg.Name,
		arg.Balance,
		arg.UpdatedAt,
	)
	return err
}
