// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: lendings.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createLending = `-- name: CreateLending :exec
INSERT INTO lendings (id, counterparty, description, amount, collected_amount, occurred_on)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateLendingParams struct {
	ID              uuid.UUID
	Counterparty    string
	Description     string
	Amount          int64
	CollectedAmount int64
	OccurredOn      time.Time
}

func (q *Queries) CreateLending(ctx context.Context, arg CreateLendingParams) error {
	_, err := q.db.ExecContext(ctx, createLending,
		arg.ID,
		arg.Counterparty,
		arg.Description,
		arg.Amount,
		arg.CollectedAmount,
		arg.OccurredOn,
	)
	return err
}

const deleteLending = `-- name: DeleteLending :exec
DELETE FROM lendings WHERE id = $1
`

func (q *Queries) DeleteLending(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteLending, id)
	return err
}

const getLending = `-- name: GetLending :one
SELECT id, counterparty, description, amount, collected_amount, occurred_on, created_at, updated_at FROM lendings WHERE id = $1
`

func (q *Queries) GetLending(ctx context.Context, id uuid.UUID) (Lending, error) {
	row := q.db.QueryRowContext(ctx, getLending, id)
	var i Lending
	err := row.Scan(
		&i.ID,
		&i.Counterparty,
		&i.Description,
		&i.Amount,
		&i.CollectedAmount,
		&i.OccurredOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLendings = `-- name: ListLendings :many
SELECT id, counterparty, description, amount, collected_amount, occurred_on, created_at, updated_at FROM lendings ORDER BY occurred_on DESC
`

func (q *Queries) ListLendings(ctx context.Context) ([]Lending, error) {
	rows, err := q.db.QueryContext(ctx, listLendings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lending{}
	for rows.Next() {
		var i Lending
		if err := rows.Scan(
			&i.ID,
			&i.Counterparty,
			&i.Description,
			&i.Amount,
			&i.CollectedAmount,
			&i.OccurredOn,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutstandingLendings = `-- name: ListOutstandingLendings :many
SELECT id, counterparty, description, amount, collected_amount, occurred_on, created_at, updated_at FROM lendings
WHERE collected_amount < amount
ORDER BY occurred_on DESC
`

func (q *Queries) ListOutstandingLendings(ctx context.Context) ([]Lending, error) {
	rows, err := q.db.QueryContext(ctx, listOutstandingLendings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lending{}
	for rows.Next() {
		var i Lending
		if err := rows.Scan(
			&i.ID,
			&i.Counterparty,
			&i.Description,
			&i.Amount,
			&i.CollectedAmount,
			&i.OccurredOn,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLendingCollectedAmount = `-- name: UpdateLendingCollectedAmount :exec
UPDATE lendings SET collected_amount = $2, updated_at = now()
WHERE id = $1
`

type UpdateLendingCollectedAmountParams struct {
	ID              uuid.UUID
	CollectedAmount int64
}

// 立替に対する更新操作は回収だけ。
//
// API は登録・回収・削除の3つで、内容を編集する PATCH は無い（design.md 5.1）。
// 全カラムを上書きするクエリを置くと、回収のついでに amount を書き換えられる
// 経路ができる。amount が動くと未回収残高（amount - collected_amount）の
// 意味が変わるため、SQL 側から塞いでおく。
//
// 加算（collected_amount + $2）にしないのは、過回収の判定を SQL に持たせない
// ため。回収後の金額は domain が検証したうえで確定させ、ここはその結果を
// 書くだけにする（不変条件4の判定責務は domain）。DB の CHECK 制約は
// 最後の防波堤として残っている。
func (q *Queries) UpdateLendingCollectedAmount(ctx context.Context, arg UpdateLendingCollectedAmountParams) error {
	_, err := q.db.ExecContext(ctx, updateLendingCollectedAmount, arg.ID, arg.CollectedAmount)
	return err
}
