// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID        uuid.UUID
	Name      string
	Kind      string
	Balance   int64
	UpdatedAt time.Time
	CreatedAt time.Time
}

type Lending struct {
	ID              uuid.UUID
	Counterparty    string
	Description     string
	Amount          int64
	CollectedAmount int64
	OccurredOn      time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type MonthlyBalance struct {
	ID        uuid.UUID
	YearMonth time.Time
	Income    int64
	Expense   int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Transaction struct {
	ID         uuid.UUID
	AccountID  uuid.UUID
	Amount     int64
	Kind       string
	RefID      uuid.NullUUID
	OccurredOn time.Time
	CreatedAt  time.Time
}

type Wish struct {
	ID        uuid.UUID
	Title     string
	Amount    int64
	Category  string
	Status    string
	Priority  int32
	Deadline  sql.NullTime
	CreatedAt time.Time
	UpdatedAt time.Time
}
