// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: monthly_balances.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listAllMonthlyBalances = `-- name: ListAllMonthlyBalances :many
SELECT id, year_month, income, expense, created_at, updated_at FROM monthly_balances ORDER BY year_month DESC
`

func (q *Queries) ListAllMonthlyBalances(ctx context.Context) ([]MonthlyBalance, error) {
	rows, err := q.db.QueryContext(ctx, listAllMonthlyBalances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonthlyBalance{}
	for rows.Next() {
		var i MonthlyBalance
		if err := rows.Scan(
			&i.ID,
			&i.YearMonth,
			&i.Income,
			&i.Expense,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentMonthlyBalances = `-- name: ListRecentMonthlyBalances :many
SELECT id, year_month, income, expense, created_at, updated_at FROM monthly_balances ORDER BY year_month DESC LIMIT $1
`

func (q *Queries) ListRecentMonthlyBalances(ctx context.Context, limit int32) ([]MonthlyBalance, error) {
	rows, err := q.db.QueryContext(ctx, listRecentMonthlyBalances, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonthlyBalance{}
	for rows.Next() {
		var i MonthlyBalance
		if err := rows.Scan(
			&i.ID,
			&i.YearMonth,
			&i.Income,
			&i.Expense,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMonthlyBalance = `-- name: UpsertMonthlyBalance :one
INSERT INTO monthly_balances (id, year_month, income, expense)
VALUES ($1, $2, $3, $4)
ON CONFLICT (year_month) DO UPDATE
SET income = EXCLUDED.income, expense = EXCLUDED.expense, updated_at = now()
RETURNING id
`

type UpsertMonthlyBalanceParams struct {
	ID        uuid.UUID
	YearMonth time.Time
	Income    int64
	Expense   int64
}

// ON CONFLICT により PUT /api/monthly-balances/{yearMonth} が冪等になる。
//
// id を返すのは、競合したときに渡した $1 が採用されないため。既存行の id は
// そのまま維持されるので、呼び出し側が生成した UUID は捨てられる。それに
// 気付かずレスポンスへ載せると、DB に存在しない id を返すことになる。
// DO UPDATE は必ず1行返すので :one で受けられる。
func (q *Queries) UpsertMonthlyBalance(ctx context.Context, arg UpsertMonthlyBalanceParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, upsertMonthlyBalance,
		arg.ID,
		arg.YearMonth,
		arg.Income,
		arg.Expense,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
