// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: transactions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTransaction = `-- name: CreateTransaction :exec
INSERT INTO transactions (id, account_id, amount, kind, ref_id, occurred_on)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateTransactionParams struct {
	ID         uuid.UUID
	AccountID  uuid.UUID
	Amount     int64
	Kind       string
	RefID      uuid.NullUUID
	OccurredOn time.Time
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) error {
	_, err := q.db.ExecContext(ctx, createTransaction,
		arg.ID,
		arg.AccountID,
		arg.Amount,
		arg.Kind,
		arg.RefID,
		arg.OccurredOn,
	)
	return err
}

const listTransactions = `-- name: ListTransactions :many

SELECT id, account_id, amount, kind, ref_id, occurred_on, created_at FROM transactions ORDER BY occurred_on DESC, created_at DESC LIMIT $1
`

// 集計クエリは書かない。実質資産の計算は Go 側の純粋関数で行う
// （CLAUDE.md 不変条件8）。
func (q *Queries) ListTransactions(ctx context.Context, limit int32) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.Kind,
			&i.RefID,
			&i.OccurredOn,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
