// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: wishes.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createWish = `-- name: CreateWish :exec
INSERT INTO wishes (id, title, amount, category, status, priority, deadline)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateWishParams struct {
	ID       uuid.UUID
	Title    string
	Amount   int64
	Category string
	Status   string
	Priority int32
	Deadline sql.NullTime
}

func (q *Queries) CreateWish(ctx context.Context, arg CreateWishParams) error {
	_, err := q.db.ExecContext(ctx, createWish,
		arg.ID,
		arg.Title,
		arg.Amount,
		arg.Category,
		arg.Status,
		arg.Priority,
		arg.Deadline,
	)
	return err
}

const deleteWish = `-- name: DeleteWish :exec
DELETE FROM wishes WHERE id = $1
`

func (q *Queries) DeleteWish(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteWish, id)
	return err
}

const getWish = `-- name: GetWish :one
SELECT id, title, amount, category, status, priority, deadline, created_at, updated_at FROM wishes WHERE id = $1
`

func (q *Queries) GetWish(ctx context.Context, id uuid.UUID) (Wish, error) {
	row := q.db.QueryRowContext(ctx, getWish, id)
	var i Wish
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Amount,
		&i.Category,
		&i.Status,
		&i.Priority,
		&i.Deadline,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWishes = `-- name: ListWishes :many
SELECT id, title, amount, category, status, priority, deadline, created_at, updated_at FROM wishes ORDER BY priority, created_at
`

func (q *Queries) ListWishes(ctx context.Context) ([]Wish, error) {
	rows, err := q.db.QueryContext(ctx, listWishes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Wish{}
	for rows.Next() {
		var i Wish
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Amount,
			&i.Category,
			&i.Status,
			&i.Priority,
			&i.Deadline,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWishesByStatus = `-- name: ListWishesByStatus :many
SELECT id, title, amount, category, status, priority, deadline, created_at, updated_at FROM wishes WHERE status = $1 ORDER BY priority, created_at
`

func (q *Queries) ListWishesByStatus(ctx context.Context, status string) ([]Wish, error) {
	rows, err := q.db.QueryContext(ctx, listWishesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Wish{}
	for rows.Next() {
		var i Wish
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Amount,
			&i.Category,
			&i.Status,
			&i.Priority,
			&i.Deadline,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWishContent = `-- name: UpdateWishContent :exec

UPDATE wishes
SET title = $2, amount = $3, priority = $4, deadline = $5, updated_at = now()
WHERE id = $1
`

type UpdateWishContentParams struct {
	ID       uuid.UUID
	Title    string
	Amount   int64
	Priority int32
	Deadline sql.NullTime
}

// 内容の更新と状態遷移でクエリを分ける。
//
// 1本の UPDATE で status も書けるようにすると、handler が
// 「PATCH で status を渡せば済む」経路を作れてしまい、遷移の可否を
// 判定する domain のエンティティメソッドを迂回できる（不変条件6）。
// SQL で書けなければ、そもそも間違えようがない。
// 内容の更新。PATCH /api/wishes/{id} が触る範囲（design.md 5.1）に対応する。
// category を含めないのは、item から goal への付け替えが API に無いため。
func (q *Queries) UpdateWishContent(ctx context.Context, arg UpdateWishContentParams) error {
	_, err := q.db.ExecContext(ctx, updateWishContent,
		arg.ID,
		arg.Title,
		arg.Amount,
		arg.Priority,
		arg.Deadline,
	)
	return err
}

const updateWishStatus = `-- name: UpdateWishStatus :exec
UPDATE wishes SET status = $2, updated_at = now()
WHERE id = $1
`

type UpdateWishStatusParams struct {
	ID     uuid.UUID
	Status string
}

// 状態遷移。/commit /pay /drop の3エンドポイントが共通で使う。
// 遷移して良いかは domain の Wish が判定済みである前提で、結果だけを書く。
func (q *Queries) UpdateWishStatus(ctx context.Context, arg UpdateWishStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateWishStatus, arg.ID, arg.Status)
	return err
}
